[project]
name = "fastapi-pilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ShubhamPawar-3333", email = "shubham.d.pawar.3333@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
fastapi-pilot = "fastapi_pilot:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
